#!/bin/bash
# necessary
sudo apt-get install ttf-mscorefonts-installer tmux curl wget git fish neofetch htop mpv gnome-tweaks trash-cli openssh-client openssh-server flameshot python3-pip python-pip tldr net-tools libreoffice preload krita xclip speedtest-cli mysql-server neovim fd-find aria2c tree gimp npm yarn apt-transport-https cowsay -yy

# teni
sudo add-apt-repository ppa:teni-ime/ibus-teni
sudo apt-get update
sudo apt-get install ibus-teni
ibus restart
sudo usermod -a -G input $USER

## C/C++/Objective-C language server
sudo apt-get install ccls -y

## git ...
sudo snap innstall grv -y

# medium unlimited
mkdir ~/tools/extenstion
cd ~/tools/extenstion
mkdir mediumUnlimited
echo "check update this 1.4.16"
wget https://manojvivek.github.io/medium-unlimited/medium-unlimited-1.4.16.zip
unzip *.zip ; rm *.zip 

# Python setup
sudo apt-get install -y python3-pandas python3-matplotlib python3-pygame
sudo pip install csvkit opencv-python
sudo pip3 install notebook pylint numpy

# brave
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install brave-browser -y

# nvim setup
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim +{PlugInstall}

# moving fish from bash
chsh -s "$(which fish)"
